Repository reactjs/react-docgen, pull requests merged in 2019-10, with the labels that each got.

#343 Assume HOC first param is Component not last
  src/utils/__tests__/resolveHOC-test.js
  src/utils/resolveHOC.js
Labels: breaking, bug

#385 Support destructuring and aliased imports in react builtin call detection
  src/utils/__tests__/isReactCloneElementCall-test.js
  src/utils/__tests__/isReactCreateClassCall-test.js
  src/utils/__tests__/isReactCreateElementCall-test.js
  src/utils/__tests__/isReactForwardRefCall-test.js
  src/utils/isReactBuiltinCall.js
  src/utils/isReactCloneElementCall.js
  src/utils/isReactCreateClassCall.js
  src/utils/isReactCreateElementCall.js
  src/utils/isReactForwardRefCall.js
Labels: bug

#344 Detect components wrapped in HOC with all resolver
  src/resolver/__tests__/findAllComponentDefinitions-test.js
  src/resolver/findAllComponentDefinitions.js
Labels: breaking

#397 Be more strict about detecting react class components
  src/handlers/__tests__/componentMethodsHandler-test.js
  src/resolver/__tests__/findAllComponentDefinitions-test.js
  src/utils/__tests__/isReactComponentClass-test.js
  src/utils/isReactComponentClass.js
Labels: bug
