Repository reactjs/react-docgen, pull requests merged in 2022-06, with the labels that each got.

#592 Support 'memo(forwardRef(...'
  src/__tests__/__snapshots__/main-test.ts.snap
  src/__tests__/fixtures/component_42.js
  src/handlers/__tests__/componentDocblockHandler-test.ts
  src/handlers/defaultPropsHandler.ts
  src/utils/__tests__/isReactForwardRefCall-test.ts
  src/utils/isReactBuiltinCall.ts
  src/utils/isReactCreateClassCall.ts
Labels: bug

#626 chore: Remove 5.x workflow from main branch
  .github/workflows/release-please-5.x.yml
  .github/workflows/release-please.yml
Labels: chore

#625 chore: Add release-please to 5.x branch
  .github/workflows/release-please.yml
Labels: 5.x, chore

#627 chore(main): release 6.0.0-alpha.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#628 fix: Fix wrong detection of forwardRef in combination with memo (#592) Backport
  src/__tests__/__snapshots__/main-test.js.snap
  src/__tests__/fixtures/component_42.js
  src/handlers/__tests__/componentDocblockHandler-test.js
  src/handlers/defaultPropsHandler.js
  src/utils/__tests__/isReactForwardRefCall-test.js
  src/utils/isReactBuiltinCall.js
  src/utils/isReactCreateClassCall.js
Labels: bug, 5.x

#630 chore: Fix release
  .github/workflows/release-please.yml
Labels: 5.x, chore

#629 chore(5.x): release 5.4.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending
